# Generated by Django 3.1 on 2020-09-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200901_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=30, null=True),
        ),
    ]
