# Generated by Django 3.1 on 2020-09-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('availability', models.CharField(blank=True, max_length=35, null=True)),
                ('image', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=35, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
