# Generated by Django 3.1 on 2020-09-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200923_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartprod',
            name='category',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
