# Generated by Django 3.1 on 2020-10-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
